require=(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({"LayerSVG":[function(require,module,exports){
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

exports.LayerSVG = (function(superClass) {
  var _insertBefore;

  extend(LayerSVG, superClass);

  function LayerSVG(options) {
    if (options == null) {
      options = {};
    }
    LayerSVG.__super__.constructor.call(this, options);
    this.shapes = {};
    this.masks = {};
    this.html = "<svg id='" + options.id + "' width='" + this.width + "' height='" + this.height + "'><defs></defs></svg>";
    this.svg = this.querySelector("#" + options.id);
  }

  LayerSVG.prototype.addShape = function(options) {
    var option, shape, value;
    if (options == null) {
      options = {};
    }
    if (options.shape === "rectangle") {
      options.shape = "rect";
    }
    shape = document.createElementNS("http://www.w3.org/2000/svg", "" + options.shape);
    for (option in options) {
      if (!hasProp.call(options, option)) continue;
      value = options[option];
      if (option !== "shape") {
        shape.setAttributeNS(null, "" + option, "" + options[option]);
      }
    }
    this.svg.appendChild(shape);
    this.shapes["" + options.id] = shape;
    return shape;
  };

  LayerSVG.prototype.addMask = function(id, shapes) {
    var defs, i, len, mask, shape;
    mask = document.createElementNS("http://www.w3.org/2000/svg", "mask");
    mask.setAttributeNS(null, "id", "" + id);
    if (!Array.isArray(shapes)) {
      shape = shapes;
      if (typeof shape === "string") {
        shape = this.svg.getElementById("" + shape);
        mask.appendChild(shape);
      } else {
        mask.appendChild(shape);
      }
    } else {
      for (i = 0, len = shapes.length; i < len; i++) {
        shape = shapes[i];
        if (typeof shape === "string") {
          shape = this.svg.getElementById("" + shape);
          mask.appendChild(shape);
        } else {
          mask.appendChild(shape);
        }
      }
    }
    defs = this.svg.getElementsByTagName("defs")[0];
    defs.appendChild(mask);
    return this.masks["" + id] = mask;
  };

  LayerSVG.prototype.addToMask = function(shapes, mask, prevShape) {
    var i, len, results, shape;
    if (!Array.isArray(shapes)) {
      shape = shapes;
      if (typeof shape === "string") {
        shape = this.svg.getElementById("" + shape);
      }
      return _insertBefore(shape, mask, prevShape);
    } else {
      results = [];
      for (i = 0, len = shapes.length; i < len; i++) {
        shape = shapes[i];
        print(shape);
        if (typeof shape === "string") {
          shape = this.svg.getElementById("" + element);
        }
        results.push(_insertBefore(shape, mask, prevShape));
      }
      return results;
    }
  };

  LayerSVG.prototype.mask = function(shape, mask) {
    if (typeof mask !== "string") {
      mask = mask.getAttributeNS(null, "id");
    }
    return shape.setAttributeNS(null, "mask", "url(#" + mask + ")");
  };

  _insertBefore = function(shape, mask, prevShape) {
    if (!prevShape) {
      return mask.appendChild(shape);
    } else {
      if (typeof prevShape === "string") {
        prevShape = this.svg.getElementById("" + prevShape);
      }
      return mask.insertBefore(shape, prevShape);
    }
  };

  return LayerSVG;

})(Layer);



},{}],"LayerSVG":[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

exports.LayerSVG = (function(superClass) {
  var _insertBefore;

  extend(LayerSVG, superClass);

  function LayerSVG(options) {
    if (options == null) {
      options = {};
    }
    LayerSVG.__super__.constructor.call(this, options);
    this.shapes = {};
    this.masks = {};
    this.html = "<svg id='" + options.id + "' width='" + this.width + "' height='" + this.height + "'><defs></defs></svg>";
    this.svg = this.querySelector("#" + options.id);
  }

  LayerSVG.prototype.addShape = function(options) {
    var option, shape, value;
    if (options == null) {
      options = {};
    }
    if (options.shape === "rectangle") {
      options.shape = "rect";
    }
    shape = document.createElementNS("http://www.w3.org/2000/svg", "" + options.shape);
    for (option in options) {
      if (!hasProp.call(options, option)) continue;
      value = options[option];
      if (option !== "shape") {
        shape.setAttributeNS(null, "" + option, "" + options[option]);
      }
    }
    this.svg.appendChild(shape);
    this.shapes["" + options.id] = shape;
    return shape;
  };

  LayerSVG.prototype.addMask = function(id, shapes) {
    var defs, i, len, mask, shape;
    mask = document.createElementNS("http://www.w3.org/2000/svg", "mask");
    mask.setAttributeNS(null, "id", "" + id);
    if (!Array.isArray(shapes)) {
      shape = shapes;
      if (typeof shape === "string") {
        shape = this.svg.getElementById("" + shape);
        mask.appendChild(shape);
      } else {
        mask.appendChild(shape);
      }
    } else {
      for (i = 0, len = shapes.length; i < len; i++) {
        shape = shapes[i];
        if (typeof shape === "string") {
          shape = this.svg.getElementById("" + shape);
          mask.appendChild(shape);
        } else {
          mask.appendChild(shape);
        }
      }
    }
    defs = this.svg.getElementsByTagName("defs")[0];
    defs.appendChild(mask);
    return this.masks["" + id] = mask;
  };

  LayerSVG.prototype.addToMask = function(shapes, mask, prevShape) {
    var i, len, results, shape;
    if (!Array.isArray(shapes)) {
      shape = shapes;
      if (typeof shape === "string") {
        shape = this.svg.getElementById("" + shape);
      }
      return _insertBefore(shape, mask, prevShape);
    } else {
      results = [];
      for (i = 0, len = shapes.length; i < len; i++) {
        shape = shapes[i];
        print(shape);
        if (typeof shape === "string") {
          shape = this.svg.getElementById("" + element);
        }
        results.push(_insertBefore(shape, mask, prevShape));
      }
      return results;
    }
  };

  LayerSVG.prototype.mask = function(shape, mask) {
    if (typeof mask !== "string") {
      mask = mask.getAttributeNS(null, "id");
    }
    return shape.setAttributeNS(null, "mask", "url(#" + mask + ")");
  };

  _insertBefore = function(shape, mask, prevShape) {
    if (!prevShape) {
      return mask.appendChild(shape);
    } else {
      if (typeof prevShape === "string") {
        prevShape = this.svg.getElementById("" + prevShape);
      }
      return mask.insertBefore(shape, prevShape);
    }
  };

  return LayerSVG;

})(Layer);

},{}],"myModule":[function(require,module,exports){
exports.myVar = "myVariable";

exports.myFunction = function() {
  return print("myFunction is running");
};

exports.myArray = [1, 2, 3];



},{}]},{},[])
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5vZGVfbW9kdWxlcy9icm93c2VyaWZ5L25vZGVfbW9kdWxlcy9icm93c2VyLXBhY2svX3ByZWx1ZGUuanMiLCIvVXNlcnMvam9zaG10dWNrZXIvR2l0SHViL0xheWVyU1ZHL0xheWVyU1ZHLmZyYW1lci9tb2R1bGVzL0xheWVyU1ZHLmNvZmZlZSIsIi4uLy4uLy4uLy4uLy4uL1VzZXJzL2pvc2htdHVja2VyL0dpdEh1Yi9MYXllclNWRy9MYXllclNWRy5mcmFtZXIvbW9kdWxlcy9MYXllclNWRy5qcyIsIi9Vc2Vycy9qb3NobXR1Y2tlci9HaXRIdWIvTGF5ZXJTVkcvTGF5ZXJTVkcuZnJhbWVyL21vZHVsZXMvbXlNb2R1bGUuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0FDQUEsSUFBQTs2QkFBQTs7QUFBQSxPQUFhLENBQUM7QUFDYixNQUFBLGFBQUE7O0FBQUEsOEJBQUEsQ0FBQTs7QUFBYSxFQUFBLGtCQUFDLE9BQUQsR0FBQTs7TUFBQyxVQUFRO0tBRXJCO0FBQUEsSUFBQSwwQ0FBTSxPQUFOLENBQUEsQ0FBQTtBQUFBLElBRUEsSUFBQyxDQUFBLE1BQUQsR0FBVSxFQUZWLENBQUE7QUFBQSxJQUdBLElBQUMsQ0FBQSxLQUFELEdBQVMsRUFIVCxDQUFBO0FBQUEsSUFJQSxJQUFDLENBQUEsSUFBRCxHQUFRLFdBQUEsR0FBWSxPQUFPLENBQUMsRUFBcEIsR0FBdUIsV0FBdkIsR0FBa0MsSUFBQyxDQUFDLEtBQXBDLEdBQTBDLFlBQTFDLEdBQXNELElBQUMsQ0FBQyxNQUF4RCxHQUErRCx1QkFKdkUsQ0FBQTtBQUFBLElBS0EsSUFBQyxDQUFBLEdBQUQsR0FBTyxJQUFDLENBQUMsYUFBRixDQUFnQixHQUFBLEdBQUksT0FBTyxDQUFDLEVBQTVCLENBTFAsQ0FGWTtFQUFBLENBQWI7O0FBQUEscUJBVUEsUUFBQSxHQUFVLFNBQUMsT0FBRCxHQUFBO0FBRVQsUUFBQSxvQkFBQTs7TUFGVSxVQUFRO0tBRWxCO0FBQUEsSUFBQSxJQUFHLE9BQU8sQ0FBQyxLQUFSLEtBQWlCLFdBQXBCO0FBQ0MsTUFBQSxPQUFPLENBQUMsS0FBUixHQUFnQixNQUFoQixDQUREO0tBQUE7QUFBQSxJQUdBLEtBQUEsR0FBUSxRQUFRLENBQUMsZUFBVCxDQUF5Qiw0QkFBekIsRUFBdUQsRUFBQSxHQUFHLE9BQU8sQ0FBQyxLQUFsRSxDQUhSLENBQUE7QUFLQSxTQUFBLGlCQUFBOzs4QkFBQTtBQUNDLE1BQUEsSUFBRyxNQUFBLEtBQVksT0FBZjtBQUNDLFFBQUEsS0FBSyxDQUFDLGNBQU4sQ0FBcUIsSUFBckIsRUFBMkIsRUFBQSxHQUFHLE1BQTlCLEVBQXdDLEVBQUEsR0FBRyxPQUFRLENBQUEsTUFBQSxDQUFuRCxDQUFBLENBREQ7T0FERDtBQUFBLEtBTEE7QUFBQSxJQVNBLElBQUMsQ0FBQSxHQUFHLENBQUMsV0FBTCxDQUFpQixLQUFqQixDQVRBLENBQUE7QUFBQSxJQVVBLElBQUMsQ0FBQSxNQUFPLENBQUEsRUFBQSxHQUFHLE9BQU8sQ0FBQyxFQUFYLENBQVIsR0FBMkIsS0FWM0IsQ0FBQTtBQVlBLFdBQU8sS0FBUCxDQWRTO0VBQUEsQ0FWVixDQUFBOztBQUFBLHFCQTBCQSxPQUFBLEdBQVMsU0FBQyxFQUFELEVBQUssTUFBTCxHQUFBO0FBQ1IsUUFBQSx5QkFBQTtBQUFBLElBQUEsSUFBQSxHQUFPLFFBQVEsQ0FBQyxlQUFULENBQXlCLDRCQUF6QixFQUF1RCxNQUF2RCxDQUFQLENBQUE7QUFBQSxJQUNBLElBQUksQ0FBQyxjQUFMLENBQW9CLElBQXBCLEVBQTBCLElBQTFCLEVBQWdDLEVBQUEsR0FBRyxFQUFuQyxDQURBLENBQUE7QUFHQSxJQUFBLElBQUcsQ0FBQSxLQUFNLENBQUMsT0FBTixDQUFjLE1BQWQsQ0FBSjtBQUNDLE1BQUEsS0FBQSxHQUFRLE1BQVIsQ0FBQTtBQUNBLE1BQUEsSUFBRyxNQUFBLENBQUEsS0FBQSxLQUFpQixRQUFwQjtBQUNDLFFBQUEsS0FBQSxHQUFRLElBQUMsQ0FBQyxHQUFHLENBQUMsY0FBTixDQUFxQixFQUFBLEdBQUcsS0FBeEIsQ0FBUixDQUFBO0FBQUEsUUFDQSxJQUFJLENBQUMsV0FBTCxDQUFpQixLQUFqQixDQURBLENBREQ7T0FBQSxNQUFBO0FBSUMsUUFBQSxJQUFJLENBQUMsV0FBTCxDQUFpQixLQUFqQixDQUFBLENBSkQ7T0FGRDtLQUFBLE1BQUE7QUFRQyxXQUFBLHdDQUFBOzBCQUFBO0FBQ0MsUUFBQSxJQUFHLE1BQUEsQ0FBQSxLQUFBLEtBQWlCLFFBQXBCO0FBQ0MsVUFBQSxLQUFBLEdBQVEsSUFBQyxDQUFDLEdBQUcsQ0FBQyxjQUFOLENBQXFCLEVBQUEsR0FBRyxLQUF4QixDQUFSLENBQUE7QUFBQSxVQUNBLElBQUksQ0FBQyxXQUFMLENBQWlCLEtBQWpCLENBREEsQ0FERDtTQUFBLE1BQUE7QUFJQyxVQUFBLElBQUksQ0FBQyxXQUFMLENBQWlCLEtBQWpCLENBQUEsQ0FKRDtTQUREO0FBQUEsT0FSRDtLQUhBO0FBQUEsSUFrQkEsSUFBQSxHQUFPLElBQUMsQ0FBQyxHQUFHLENBQUMsb0JBQU4sQ0FBMkIsTUFBM0IsQ0FBbUMsQ0FBQSxDQUFBLENBbEIxQyxDQUFBO0FBQUEsSUFtQkEsSUFBSSxDQUFDLFdBQUwsQ0FBaUIsSUFBakIsQ0FuQkEsQ0FBQTtXQW9CQSxJQUFDLENBQUEsS0FBTSxDQUFBLEVBQUEsR0FBRyxFQUFILENBQVAsR0FBa0IsS0FyQlY7RUFBQSxDQTFCVCxDQUFBOztBQUFBLHFCQWlEQSxTQUFBLEdBQVcsU0FBQyxNQUFELEVBQVMsSUFBVCxFQUFlLFNBQWYsR0FBQTtBQUNWLFFBQUEsc0JBQUE7QUFBQSxJQUFBLElBQUcsQ0FBQSxLQUFNLENBQUMsT0FBTixDQUFjLE1BQWQsQ0FBSjtBQUNDLE1BQUEsS0FBQSxHQUFRLE1BQVIsQ0FBQTtBQUNBLE1BQUEsSUFBRyxNQUFBLENBQUEsS0FBQSxLQUFpQixRQUFwQjtBQUNDLFFBQUEsS0FBQSxHQUFRLElBQUMsQ0FBQyxHQUFHLENBQUMsY0FBTixDQUFxQixFQUFBLEdBQUcsS0FBeEIsQ0FBUixDQUREO09BREE7YUFJQSxhQUFBLENBQWMsS0FBZCxFQUFxQixJQUFyQixFQUEyQixTQUEzQixFQUxEO0tBQUEsTUFBQTtBQU9DO1dBQUEsd0NBQUE7MEJBQUE7QUFDQyxRQUFBLEtBQUEsQ0FBTSxLQUFOLENBQUEsQ0FBQTtBQUNBLFFBQUEsSUFBRyxNQUFBLENBQUEsS0FBQSxLQUFpQixRQUFwQjtBQUNDLFVBQUEsS0FBQSxHQUFRLElBQUMsQ0FBQyxHQUFHLENBQUMsY0FBTixDQUFxQixFQUFBLEdBQUcsT0FBeEIsQ0FBUixDQUREO1NBREE7QUFBQSxxQkFJQSxhQUFBLENBQWMsS0FBZCxFQUFxQixJQUFyQixFQUEyQixTQUEzQixFQUpBLENBREQ7QUFBQTtxQkFQRDtLQURVO0VBQUEsQ0FqRFgsQ0FBQTs7QUFBQSxxQkFnRUEsSUFBQSxHQUFNLFNBQUMsS0FBRCxFQUFRLElBQVIsR0FBQTtBQUNMLElBQUEsSUFBRyxNQUFBLENBQUEsSUFBQSxLQUFrQixRQUFyQjtBQUNDLE1BQUEsSUFBQSxHQUFPLElBQUksQ0FBQyxjQUFMLENBQW9CLElBQXBCLEVBQTBCLElBQTFCLENBQVAsQ0FERDtLQUFBO1dBR0EsS0FBSyxDQUFDLGNBQU4sQ0FBcUIsSUFBckIsRUFBMkIsTUFBM0IsRUFBbUMsT0FBQSxHQUFRLElBQVIsR0FBYSxHQUFoRCxFQUpLO0VBQUEsQ0FoRU4sQ0FBQTs7QUFBQSxFQXNFQSxhQUFBLEdBQWdCLFNBQUMsS0FBRCxFQUFRLElBQVIsRUFBYyxTQUFkLEdBQUE7QUFDZixJQUFBLElBQUcsQ0FBQSxTQUFIO2FBQ0MsSUFBSSxDQUFDLFdBQUwsQ0FBaUIsS0FBakIsRUFERDtLQUFBLE1BQUE7QUFHQyxNQUFBLElBQUcsTUFBQSxDQUFBLFNBQUEsS0FBcUIsUUFBeEI7QUFDQyxRQUFBLFNBQUEsR0FBWSxJQUFDLENBQUMsR0FBRyxDQUFDLGNBQU4sQ0FBcUIsRUFBQSxHQUFHLFNBQXhCLENBQVosQ0FERDtPQUFBO2FBR0EsSUFBSSxDQUFDLFlBQUwsQ0FBa0IsS0FBbEIsRUFBeUIsU0FBekIsRUFORDtLQURlO0VBQUEsQ0F0RWhCLENBQUE7O2tCQUFBOztHQUQ4QixNQUEvQixDQUFBOzs7OztBQ0FBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7O0FDNUdBLE9BQU8sQ0FBQyxLQUFSLEdBQWdCLFlBQWhCLENBQUE7O0FBQUEsT0FFTyxDQUFDLFVBQVIsR0FBcUIsU0FBQSxHQUFBO1NBQ3BCLEtBQUEsQ0FBTSx1QkFBTixFQURvQjtBQUFBLENBRnJCLENBQUE7O0FBQUEsT0FLTyxDQUFDLE9BQVIsR0FBa0IsQ0FBQyxDQUFELEVBQUksQ0FBSixFQUFPLENBQVAsQ0FMbEIsQ0FBQSIsImZpbGUiOiJnZW5lcmF0ZWQuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlc0NvbnRlbnQiOlsiKGZ1bmN0aW9uIGUodCxuLHIpe2Z1bmN0aW9uIHMobyx1KXtpZighbltvXSl7aWYoIXRbb10pe3ZhciBhPXR5cGVvZiByZXF1aXJlPT1cImZ1bmN0aW9uXCImJnJlcXVpcmU7aWYoIXUmJmEpcmV0dXJuIGEobywhMCk7aWYoaSlyZXR1cm4gaShvLCEwKTt2YXIgZj1uZXcgRXJyb3IoXCJDYW5ub3QgZmluZCBtb2R1bGUgJ1wiK28rXCInXCIpO3Rocm93IGYuY29kZT1cIk1PRFVMRV9OT1RfRk9VTkRcIixmfXZhciBsPW5bb109e2V4cG9ydHM6e319O3Rbb11bMF0uY2FsbChsLmV4cG9ydHMsZnVuY3Rpb24oZSl7dmFyIG49dFtvXVsxXVtlXTtyZXR1cm4gcyhuP246ZSl9LGwsbC5leHBvcnRzLGUsdCxuLHIpfXJldHVybiBuW29dLmV4cG9ydHN9dmFyIGk9dHlwZW9mIHJlcXVpcmU9PVwiZnVuY3Rpb25cIiYmcmVxdWlyZTtmb3IodmFyIG89MDtvPHIubGVuZ3RoO28rKylzKHJbb10pO3JldHVybiBzfSkiLCJjbGFzcyBleHBvcnRzLkxheWVyU1ZHIGV4dGVuZHMgTGF5ZXIgXG5cdGNvbnN0cnVjdG9yOiAob3B0aW9ucz17fSkgLT5cblx0XHRcblx0XHRzdXBlciBvcHRpb25zXG5cblx0XHRAc2hhcGVzID0ge31cblx0XHRAbWFza3MgPSB7fVxuXHRcdEBodG1sID0gXCI8c3ZnIGlkPScje29wdGlvbnMuaWR9JyB3aWR0aD0nI3tALndpZHRofScgaGVpZ2h0PScje0AuaGVpZ2h0fSc+PGRlZnM+PC9kZWZzPjwvc3ZnPlwiXG5cdFx0QHN2ZyA9IEAucXVlcnlTZWxlY3RvcihcIiMje29wdGlvbnMuaWR9XCIpXHRcblxuXG5cdGFkZFNoYXBlOiAob3B0aW9ucz17fSkgLT5cblxuXHRcdGlmIG9wdGlvbnMuc2hhcGUgaXMgXCJyZWN0YW5nbGVcIlxuXHRcdFx0b3B0aW9ucy5zaGFwZSA9IFwicmVjdFwiXG5cblx0XHRzaGFwZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnROUyhcImh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnXCIsIFwiI3tvcHRpb25zLnNoYXBlfVwiKSBcblxuXHRcdGZvciBvd24gb3B0aW9uLCB2YWx1ZSBvZiBvcHRpb25zXG5cdFx0XHRpZiBvcHRpb24gaXNudCBcInNoYXBlXCJcblx0XHRcdFx0c2hhcGUuc2V0QXR0cmlidXRlTlMobnVsbCwgXCIje29wdGlvbn1cIiwgXCIje29wdGlvbnNbb3B0aW9uXX1cIilcblxuXHRcdEBzdmcuYXBwZW5kQ2hpbGQoc2hhcGUpXG5cdFx0QHNoYXBlc1tcIiN7b3B0aW9ucy5pZH1cIl0gPSBzaGFwZVxuXG5cdFx0cmV0dXJuIHNoYXBlXG5cblx0YWRkTWFzazogKGlkLCBzaGFwZXMpIC0+XG5cdFx0bWFzayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnROUyhcImh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnXCIsIFwibWFza1wiKVxuXHRcdG1hc2suc2V0QXR0cmlidXRlTlMobnVsbCwgXCJpZFwiLCBcIiN7aWR9XCIpXG5cblx0XHRpZiAhQXJyYXkuaXNBcnJheShzaGFwZXMpXG5cdFx0XHRzaGFwZSA9IHNoYXBlc1xuXHRcdFx0aWYgdHlwZW9mKHNoYXBlKSBpcyBcInN0cmluZ1wiXG5cdFx0XHRcdHNoYXBlID0gQC5zdmcuZ2V0RWxlbWVudEJ5SWQoXCIje3NoYXBlfVwiKVxuXHRcdFx0XHRtYXNrLmFwcGVuZENoaWxkKHNoYXBlKVxuXHRcdFx0ZWxzZVxuXHRcdFx0XHRtYXNrLmFwcGVuZENoaWxkKHNoYXBlKVxuXHRcdGVsc2Vcblx0XHRcdGZvciBzaGFwZSBpbiBzaGFwZXMgXG5cdFx0XHRcdGlmIHR5cGVvZihzaGFwZSkgaXMgXCJzdHJpbmdcIlxuXHRcdFx0XHRcdHNoYXBlID0gQC5zdmcuZ2V0RWxlbWVudEJ5SWQoXCIje3NoYXBlfVwiKVxuXHRcdFx0XHRcdG1hc2suYXBwZW5kQ2hpbGQoc2hhcGUpXG5cdFx0XHRcdGVsc2Vcblx0XHRcdFx0XHRtYXNrLmFwcGVuZENoaWxkKHNoYXBlKVxuXG5cdFx0ZGVmcyA9IEAuc3ZnLmdldEVsZW1lbnRzQnlUYWdOYW1lKFwiZGVmc1wiKVswXVxuXHRcdGRlZnMuYXBwZW5kQ2hpbGQobWFzaylcblx0XHRAbWFza3NbXCIje2lkfVwiXSA9IG1hc2tcblxuXHRhZGRUb01hc2s6IChzaGFwZXMsIG1hc2ssIHByZXZTaGFwZSkgLT5cblx0XHRpZiAhQXJyYXkuaXNBcnJheShzaGFwZXMpXG5cdFx0XHRzaGFwZSA9IHNoYXBlc1xuXHRcdFx0aWYgdHlwZW9mKHNoYXBlKSBpcyBcInN0cmluZ1wiXG5cdFx0XHRcdHNoYXBlID0gQC5zdmcuZ2V0RWxlbWVudEJ5SWQoXCIje3NoYXBlfVwiKVxuXG5cdFx0XHRfaW5zZXJ0QmVmb3JlKHNoYXBlLCBtYXNrLCBwcmV2U2hhcGUpXG5cdFx0ZWxzZVxuXHRcdFx0Zm9yIHNoYXBlIGluIHNoYXBlc1xuXHRcdFx0XHRwcmludCBzaGFwZVxuXHRcdFx0XHRpZiB0eXBlb2Yoc2hhcGUpIGlzIFwic3RyaW5nXCJcblx0XHRcdFx0XHRzaGFwZSA9IEAuc3ZnLmdldEVsZW1lbnRCeUlkKFwiI3tlbGVtZW50fVwiKVxuXG5cdFx0XHRcdF9pbnNlcnRCZWZvcmUoc2hhcGUsIG1hc2ssIHByZXZTaGFwZSlcblxuXHRtYXNrOiAoc2hhcGUsIG1hc2spIC0+XG5cdFx0aWYgdHlwZW9mKG1hc2spIGlzbnQgXCJzdHJpbmdcIlxuXHRcdFx0bWFzayA9IG1hc2suZ2V0QXR0cmlidXRlTlMobnVsbCwgXCJpZFwiKVxuXG5cdFx0c2hhcGUuc2V0QXR0cmlidXRlTlMobnVsbCwgXCJtYXNrXCIsIFwidXJsKCMje21hc2t9KVwiKVxuXG5cdF9pbnNlcnRCZWZvcmUgPSAoc2hhcGUsIG1hc2ssIHByZXZTaGFwZSkgLT5cblx0XHRpZiAhcHJldlNoYXBlXG5cdFx0XHRtYXNrLmFwcGVuZENoaWxkKHNoYXBlKVxuXHRcdGVsc2UgXG5cdFx0XHRpZiB0eXBlb2YocHJldlNoYXBlKSBpcyBcInN0cmluZ1wiXG5cdFx0XHRcdHByZXZTaGFwZSA9IEAuc3ZnLmdldEVsZW1lbnRCeUlkKFwiI3twcmV2U2hhcGV9XCIpXG5cblx0XHRcdG1hc2suaW5zZXJ0QmVmb3JlKHNoYXBlLCBwcmV2U2hhcGUpXG5cdFx0IiwiLy8gR2VuZXJhdGVkIGJ5IENvZmZlZVNjcmlwdCAxLjkuMVxudmFyIGV4dGVuZCA9IGZ1bmN0aW9uKGNoaWxkLCBwYXJlbnQpIHsgZm9yICh2YXIga2V5IGluIHBhcmVudCkgeyBpZiAoaGFzUHJvcC5jYWxsKHBhcmVudCwga2V5KSkgY2hpbGRba2V5XSA9IHBhcmVudFtrZXldOyB9IGZ1bmN0aW9uIGN0b3IoKSB7IHRoaXMuY29uc3RydWN0b3IgPSBjaGlsZDsgfSBjdG9yLnByb3RvdHlwZSA9IHBhcmVudC5wcm90b3R5cGU7IGNoaWxkLnByb3RvdHlwZSA9IG5ldyBjdG9yKCk7IGNoaWxkLl9fc3VwZXJfXyA9IHBhcmVudC5wcm90b3R5cGU7IHJldHVybiBjaGlsZDsgfSxcbiAgaGFzUHJvcCA9IHt9Lmhhc093blByb3BlcnR5O1xuXG5leHBvcnRzLkxheWVyU1ZHID0gKGZ1bmN0aW9uKHN1cGVyQ2xhc3MpIHtcbiAgdmFyIF9pbnNlcnRCZWZvcmU7XG5cbiAgZXh0ZW5kKExheWVyU1ZHLCBzdXBlckNsYXNzKTtcblxuICBmdW5jdGlvbiBMYXllclNWRyhvcHRpb25zKSB7XG4gICAgaWYgKG9wdGlvbnMgPT0gbnVsbCkge1xuICAgICAgb3B0aW9ucyA9IHt9O1xuICAgIH1cbiAgICBMYXllclNWRy5fX3N1cGVyX18uY29uc3RydWN0b3IuY2FsbCh0aGlzLCBvcHRpb25zKTtcbiAgICB0aGlzLnNoYXBlcyA9IHt9O1xuICAgIHRoaXMubWFza3MgPSB7fTtcbiAgICB0aGlzLmh0bWwgPSBcIjxzdmcgaWQ9J1wiICsgb3B0aW9ucy5pZCArIFwiJyB3aWR0aD0nXCIgKyB0aGlzLndpZHRoICsgXCInIGhlaWdodD0nXCIgKyB0aGlzLmhlaWdodCArIFwiJz48ZGVmcz48L2RlZnM+PC9zdmc+XCI7XG4gICAgdGhpcy5zdmcgPSB0aGlzLnF1ZXJ5U2VsZWN0b3IoXCIjXCIgKyBvcHRpb25zLmlkKTtcbiAgfVxuXG4gIExheWVyU1ZHLnByb3RvdHlwZS5hZGRTaGFwZSA9IGZ1bmN0aW9uKG9wdGlvbnMpIHtcbiAgICB2YXIgb3B0aW9uLCBzaGFwZSwgdmFsdWU7XG4gICAgaWYgKG9wdGlvbnMgPT0gbnVsbCkge1xuICAgICAgb3B0aW9ucyA9IHt9O1xuICAgIH1cbiAgICBpZiAob3B0aW9ucy5zaGFwZSA9PT0gXCJyZWN0YW5nbGVcIikge1xuICAgICAgb3B0aW9ucy5zaGFwZSA9IFwicmVjdFwiO1xuICAgIH1cbiAgICBzaGFwZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnROUyhcImh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnXCIsIFwiXCIgKyBvcHRpb25zLnNoYXBlKTtcbiAgICBmb3IgKG9wdGlvbiBpbiBvcHRpb25zKSB7XG4gICAgICBpZiAoIWhhc1Byb3AuY2FsbChvcHRpb25zLCBvcHRpb24pKSBjb250aW51ZTtcbiAgICAgIHZhbHVlID0gb3B0aW9uc1tvcHRpb25dO1xuICAgICAgaWYgKG9wdGlvbiAhPT0gXCJzaGFwZVwiKSB7XG4gICAgICAgIHNoYXBlLnNldEF0dHJpYnV0ZU5TKG51bGwsIFwiXCIgKyBvcHRpb24sIFwiXCIgKyBvcHRpb25zW29wdGlvbl0pO1xuICAgICAgfVxuICAgIH1cbiAgICB0aGlzLnN2Zy5hcHBlbmRDaGlsZChzaGFwZSk7XG4gICAgdGhpcy5zaGFwZXNbXCJcIiArIG9wdGlvbnMuaWRdID0gc2hhcGU7XG4gICAgcmV0dXJuIHNoYXBlO1xuICB9O1xuXG4gIExheWVyU1ZHLnByb3RvdHlwZS5hZGRNYXNrID0gZnVuY3Rpb24oaWQsIHNoYXBlcykge1xuICAgIHZhciBkZWZzLCBpLCBsZW4sIG1hc2ssIHNoYXBlO1xuICAgIG1hc2sgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50TlMoXCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiLCBcIm1hc2tcIik7XG4gICAgbWFzay5zZXRBdHRyaWJ1dGVOUyhudWxsLCBcImlkXCIsIFwiXCIgKyBpZCk7XG4gICAgaWYgKCFBcnJheS5pc0FycmF5KHNoYXBlcykpIHtcbiAgICAgIHNoYXBlID0gc2hhcGVzO1xuICAgICAgaWYgKHR5cGVvZiBzaGFwZSA9PT0gXCJzdHJpbmdcIikge1xuICAgICAgICBzaGFwZSA9IHRoaXMuc3ZnLmdldEVsZW1lbnRCeUlkKFwiXCIgKyBzaGFwZSk7XG4gICAgICAgIG1hc2suYXBwZW5kQ2hpbGQoc2hhcGUpO1xuICAgICAgfSBlbHNlIHtcbiAgICAgICAgbWFzay5hcHBlbmRDaGlsZChzaGFwZSk7XG4gICAgICB9XG4gICAgfSBlbHNlIHtcbiAgICAgIGZvciAoaSA9IDAsIGxlbiA9IHNoYXBlcy5sZW5ndGg7IGkgPCBsZW47IGkrKykge1xuICAgICAgICBzaGFwZSA9IHNoYXBlc1tpXTtcbiAgICAgICAgaWYgKHR5cGVvZiBzaGFwZSA9PT0gXCJzdHJpbmdcIikge1xuICAgICAgICAgIHNoYXBlID0gdGhpcy5zdmcuZ2V0RWxlbWVudEJ5SWQoXCJcIiArIHNoYXBlKTtcbiAgICAgICAgICBtYXNrLmFwcGVuZENoaWxkKHNoYXBlKTtcbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICBtYXNrLmFwcGVuZENoaWxkKHNoYXBlKTtcbiAgICAgICAgfVxuICAgICAgfVxuICAgIH1cbiAgICBkZWZzID0gdGhpcy5zdmcuZ2V0RWxlbWVudHNCeVRhZ05hbWUoXCJkZWZzXCIpWzBdO1xuICAgIGRlZnMuYXBwZW5kQ2hpbGQobWFzayk7XG4gICAgcmV0dXJuIHRoaXMubWFza3NbXCJcIiArIGlkXSA9IG1hc2s7XG4gIH07XG5cbiAgTGF5ZXJTVkcucHJvdG90eXBlLmFkZFRvTWFzayA9IGZ1bmN0aW9uKHNoYXBlcywgbWFzaywgcHJldlNoYXBlKSB7XG4gICAgdmFyIGksIGxlbiwgcmVzdWx0cywgc2hhcGU7XG4gICAgaWYgKCFBcnJheS5pc0FycmF5KHNoYXBlcykpIHtcbiAgICAgIHNoYXBlID0gc2hhcGVzO1xuICAgICAgaWYgKHR5cGVvZiBzaGFwZSA9PT0gXCJzdHJpbmdcIikge1xuICAgICAgICBzaGFwZSA9IHRoaXMuc3ZnLmdldEVsZW1lbnRCeUlkKFwiXCIgKyBzaGFwZSk7XG4gICAgICB9XG4gICAgICByZXR1cm4gX2luc2VydEJlZm9yZShzaGFwZSwgbWFzaywgcHJldlNoYXBlKTtcbiAgICB9IGVsc2Uge1xuICAgICAgcmVzdWx0cyA9IFtdO1xuICAgICAgZm9yIChpID0gMCwgbGVuID0gc2hhcGVzLmxlbmd0aDsgaSA8IGxlbjsgaSsrKSB7XG4gICAgICAgIHNoYXBlID0gc2hhcGVzW2ldO1xuICAgICAgICBwcmludChzaGFwZSk7XG4gICAgICAgIGlmICh0eXBlb2Ygc2hhcGUgPT09IFwic3RyaW5nXCIpIHtcbiAgICAgICAgICBzaGFwZSA9IHRoaXMuc3ZnLmdldEVsZW1lbnRCeUlkKFwiXCIgKyBlbGVtZW50KTtcbiAgICAgICAgfVxuICAgICAgICByZXN1bHRzLnB1c2goX2luc2VydEJlZm9yZShzaGFwZSwgbWFzaywgcHJldlNoYXBlKSk7XG4gICAgICB9XG4gICAgICByZXR1cm4gcmVzdWx0cztcbiAgICB9XG4gIH07XG5cbiAgTGF5ZXJTVkcucHJvdG90eXBlLm1hc2sgPSBmdW5jdGlvbihzaGFwZSwgbWFzaykge1xuICAgIGlmICh0eXBlb2YgbWFzayAhPT0gXCJzdHJpbmdcIikge1xuICAgICAgbWFzayA9IG1hc2suZ2V0QXR0cmlidXRlTlMobnVsbCwgXCJpZFwiKTtcbiAgICB9XG4gICAgcmV0dXJuIHNoYXBlLnNldEF0dHJpYnV0ZU5TKG51bGwsIFwibWFza1wiLCBcInVybCgjXCIgKyBtYXNrICsgXCIpXCIpO1xuICB9O1xuXG4gIF9pbnNlcnRCZWZvcmUgPSBmdW5jdGlvbihzaGFwZSwgbWFzaywgcHJldlNoYXBlKSB7XG4gICAgaWYgKCFwcmV2U2hhcGUpIHtcbiAgICAgIHJldHVybiBtYXNrLmFwcGVuZENoaWxkKHNoYXBlKTtcbiAgICB9IGVsc2Uge1xuICAgICAgaWYgKHR5cGVvZiBwcmV2U2hhcGUgPT09IFwic3RyaW5nXCIpIHtcbiAgICAgICAgcHJldlNoYXBlID0gdGhpcy5zdmcuZ2V0RWxlbWVudEJ5SWQoXCJcIiArIHByZXZTaGFwZSk7XG4gICAgICB9XG4gICAgICByZXR1cm4gbWFzay5pbnNlcnRCZWZvcmUoc2hhcGUsIHByZXZTaGFwZSk7XG4gICAgfVxuICB9O1xuXG4gIHJldHVybiBMYXllclNWRztcblxufSkoTGF5ZXIpO1xuIiwiIyBBZGQgdGhlIGZvbGxvd2luZyBsaW5lIHRvIHlvdXIgcHJvamVjdCBpbiBGcmFtZXIgU3R1ZGlvLiBcbiMgbXlNb2R1bGUgPSByZXF1aXJlIFwibXlNb2R1bGVcIlxuIyBSZWZlcmVuY2UgdGhlIGNvbnRlbnRzIGJ5IG5hbWUsIGxpa2UgbXlNb2R1bGUubXlGdW5jdGlvbigpIG9yIG15TW9kdWxlLm15VmFyXG5cbmV4cG9ydHMubXlWYXIgPSBcIm15VmFyaWFibGVcIlxuXG5leHBvcnRzLm15RnVuY3Rpb24gPSAtPlxuXHRwcmludCBcIm15RnVuY3Rpb24gaXMgcnVubmluZ1wiXG5cbmV4cG9ydHMubXlBcnJheSA9IFsxLCAyLCAzXSJdfQ==
