require=(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({"LayerSVG":[function(require,module,exports){
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

exports.LayerSVG = (function(superClass) {
  extend(LayerSVG, superClass);

  function LayerSVG(options) {
    if (options == null) {
      options = {};
    }
    LayerSVG.__super__.constructor.call(this, options);
    this.html = "<svg id='" + options.id + "' width='" + this.width + "' height='" + this.height + "'><defs></defs></svg>";
    this.svg = this.querySelector("#" + options.id);
    this.shapes = {};
    this.masks = {};
    this.clipPaths = {};
  }

  LayerSVG.prototype.addShape = function(options) {
    var option, shape, value;
    if (options == null) {
      options = {};
    }
    shape = document.createElementNS("http://www.w3.org/2000/svg", "" + options.shape);
    for (option in options) {
      if (!hasProp.call(options, option)) continue;
      value = options[option];
      if (option !== "shape") {
        shape.setAttributeNS(null, "" + option, "" + options[option]);
      }
    }
    this.svg.appendChild(shape);
    this.shapes["" + options.id] = shape;
    return shape;
  };

  LayerSVG.prototype.addDef = function(options) {
    var def, defs, i, len, ref, shape;
    if (options == null) {
      options = {};
    }
    def = document.createElementNS("http://www.w3.org/2000/svg", "" + options.type);
    def.setAttributeNS(null, "id", "" + options.id);
    if (def === "clipPath" || "mask") {
      ref = options.shapes;
      for (i = 0, len = ref.length; i < len; i++) {
        shape = ref[i];
        if (typeof shape === "string") {
          shape = this.svg.getElementById("" + shape);
        }
        def.appendChild(shape);
      }
    }
    defs = this.svg.getElementsByTagName("defs")[0];
    defs.appendChild(def);
    if (options.type === "clipPath") {
      return this.clipPaths["" + options.id] = def;
    } else {
      return this.masks["" + options.id] = def;
    }
  };

  LayerSVG.prototype.addToDef = function(elements, def, prevElement) {
    var element, i, len, results;
    if (typeof def === "string") {
      def = this.svg.getElementById("" + def);
    }
    if (!Array.isArray(elements)) {
      element = elements;
      if (typeof element === "string") {
        element = this.svg.getElementById("" + element);
      }
      if (!prevElement) {
        return def.appendChild(ele);
      } else {
        return def.insertBefore(element, prevElement);
      }
    } else {
      results = [];
      for (i = 0, len = elements.length; i < len; i++) {
        element = elements[i];
        if (typeof element === "string") {
          element = this.svg.getElementById("" + element);
        }
        if (!prevElement) {
          results.push(def.appendChild(element));
        } else {
          results.push(def.insertBefore(element, prevElement));
        }
      }
      return results;
    }
  };

  LayerSVG.prototype.mask = function(shape, mask) {
    if (typeof shape === "string") {
      shape = this.svg.getElementById("" + shape);
    }
    if (typeof mask !== "string") {
      mask = mask.getAttributeNS(null, "id");
    }
    return shape.setAttributeNS(null, "mask", "url(#" + mask + ")");
  };

  return LayerSVG;

})(Layer);



},{}],"LayerSVG":[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

exports.LayerSVG = (function(superClass) {
  extend(LayerSVG, superClass);

  function LayerSVG(options) {
    if (options == null) {
      options = {};
    }
    LayerSVG.__super__.constructor.call(this, options);
    this.html = "<svg id='" + options.id + "' width='" + this.width + "' height='" + this.height + "'><defs></defs></svg>";
    this.svg = this.querySelector("#" + options.id);
    this.shapes = {};
    this.masks = {};
    this.clipPaths = {};
  }

  LayerSVG.prototype.addShape = function(options) {
    var option, shape, value;
    if (options == null) {
      options = {};
    }
    shape = document.createElementNS("http://www.w3.org/2000/svg", "" + options.shape);
    for (option in options) {
      if (!hasProp.call(options, option)) continue;
      value = options[option];
      if (option !== "shape") {
        shape.setAttributeNS(null, "" + option, "" + options[option]);
      }
    }
    this.svg.appendChild(shape);
    this.shapes["" + options.id] = shape;
    return shape;
  };

  LayerSVG.prototype.addDef = function(options) {
    var def, defs, i, len, ref, shape;
    if (options == null) {
      options = {};
    }
    def = document.createElementNS("http://www.w3.org/2000/svg", "" + options.type);
    def.setAttributeNS(null, "id", "" + options.id);
    if (def === "clipPath" || "mask") {
      ref = options.shapes;
      for (i = 0, len = ref.length; i < len; i++) {
        shape = ref[i];
        if (typeof shape === "string") {
          shape = this.svg.getElementById("" + shape);
        }
        def.appendChild(shape);
      }
    }
    defs = this.svg.getElementsByTagName("defs")[0];
    defs.appendChild(def);
    if (options.type === "clipPath") {
      return this.clipPaths["" + options.id] = def;
    } else {
      return this.masks["" + options.id] = def;
    }
  };

  LayerSVG.prototype.addToDef = function(elements, def, prevElement) {
    var element, i, len, results;
    if (typeof def === "string") {
      def = this.svg.getElementById("" + def);
    }
    if (!Array.isArray(elements)) {
      element = elements;
      if (typeof element === "string") {
        element = this.svg.getElementById("" + element);
      }
      if (!prevElement) {
        return def.appendChild(ele);
      } else {
        return def.insertBefore(element, prevElement);
      }
    } else {
      results = [];
      for (i = 0, len = elements.length; i < len; i++) {
        element = elements[i];
        if (typeof element === "string") {
          element = this.svg.getElementById("" + element);
        }
        if (!prevElement) {
          results.push(def.appendChild(element));
        } else {
          results.push(def.insertBefore(element, prevElement));
        }
      }
      return results;
    }
  };

  LayerSVG.prototype.mask = function(shape, mask) {
    if (typeof shape === "string") {
      shape = this.svg.getElementById("" + shape);
    }
    if (typeof mask !== "string") {
      mask = mask.getAttributeNS(null, "id");
    }
    return shape.setAttributeNS(null, "mask", "url(#" + mask + ")");
  };

  return LayerSVG;

})(Layer);

},{}],"myModule":[function(require,module,exports){
exports.myVar = "myVariable";

exports.myFunction = function() {
  return print("myFunction is running");
};

exports.myArray = [1, 2, 3];



},{}]},{},[])
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5vZGVfbW9kdWxlcy9icm93c2VyaWZ5L25vZGVfbW9kdWxlcy9icm93c2VyLXBhY2svX3ByZWx1ZGUuanMiLCIvVXNlcnMvam9zaG10dWNrZXIvR2l0SHViL0xheWVyU1ZHL0xheWVyU1ZHLmZyYW1lci9tb2R1bGVzL0xheWVyU1ZHLmNvZmZlZSIsIi4uLy4uLy4uLy4uLy4uL1VzZXJzL2pvc2htdHVja2VyL0dpdEh1Yi9MYXllclNWRy9MYXllclNWRy5mcmFtZXIvbW9kdWxlcy9MYXllclNWRy5qcyIsIi9Vc2Vycy9qb3NobXR1Y2tlci9HaXRIdWIvTGF5ZXJTVkcvTGF5ZXJTVkcuZnJhbWVyL21vZHVsZXMvbXlNb2R1bGUuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0FDQUEsSUFBQTs2QkFBQTs7QUFBQSxPQUFhLENBQUM7QUFDYiw4QkFBQSxDQUFBOztBQUFhLEVBQUEsa0JBQUMsT0FBRCxHQUFBOztNQUFDLFVBQVE7S0FFckI7QUFBQSxJQUFBLDBDQUFNLE9BQU4sQ0FBQSxDQUFBO0FBQUEsSUFFQSxJQUFDLENBQUEsSUFBRCxHQUFRLFdBQUEsR0FBWSxPQUFPLENBQUMsRUFBcEIsR0FBdUIsV0FBdkIsR0FBa0MsSUFBQyxDQUFDLEtBQXBDLEdBQTBDLFlBQTFDLEdBQXNELElBQUMsQ0FBQyxNQUF4RCxHQUErRCx1QkFGdkUsQ0FBQTtBQUFBLElBR0EsSUFBQyxDQUFBLEdBQUQsR0FBTyxJQUFDLENBQUMsYUFBRixDQUFnQixHQUFBLEdBQUksT0FBTyxDQUFDLEVBQTVCLENBSFAsQ0FBQTtBQUFBLElBS0EsSUFBQyxDQUFBLE1BQUQsR0FBVSxFQUxWLENBQUE7QUFBQSxJQU1BLElBQUMsQ0FBQSxLQUFELEdBQVMsRUFOVCxDQUFBO0FBQUEsSUFPQSxJQUFDLENBQUEsU0FBRCxHQUFhLEVBUGIsQ0FGWTtFQUFBLENBQWI7O0FBQUEscUJBV0EsUUFBQSxHQUFVLFNBQUMsT0FBRCxHQUFBO0FBQ1QsUUFBQSxvQkFBQTs7TUFEVSxVQUFRO0tBQ2xCO0FBQUEsSUFBQSxLQUFBLEdBQVEsUUFBUSxDQUFDLGVBQVQsQ0FBeUIsNEJBQXpCLEVBQXVELEVBQUEsR0FBRyxPQUFPLENBQUMsS0FBbEUsQ0FBUixDQUFBO0FBRUEsU0FBQSxpQkFBQTs7OEJBQUE7QUFDRSxNQUFBLElBQUcsTUFBQSxLQUFZLE9BQWY7QUFDQyxRQUFBLEtBQUssQ0FBQyxjQUFOLENBQXFCLElBQXJCLEVBQTJCLEVBQUEsR0FBRyxNQUE5QixFQUF3QyxFQUFBLEdBQUcsT0FBUSxDQUFBLE1BQUEsQ0FBbkQsQ0FBQSxDQUREO09BREY7QUFBQSxLQUZBO0FBQUEsSUFNQSxJQUFDLENBQUEsR0FBRyxDQUFDLFdBQUwsQ0FBaUIsS0FBakIsQ0FOQSxDQUFBO0FBQUEsSUFPQSxJQUFDLENBQUEsTUFBTyxDQUFBLEVBQUEsR0FBRyxPQUFPLENBQUMsRUFBWCxDQUFSLEdBQTJCLEtBUDNCLENBQUE7QUFTQSxXQUFPLEtBQVAsQ0FWUztFQUFBLENBWFYsQ0FBQTs7QUFBQSxxQkF1QkEsTUFBQSxHQUFRLFNBQUMsT0FBRCxHQUFBO0FBQ1AsUUFBQSw2QkFBQTs7TUFEUSxVQUFRO0tBQ2hCO0FBQUEsSUFBQSxHQUFBLEdBQU0sUUFBUSxDQUFDLGVBQVQsQ0FBeUIsNEJBQXpCLEVBQXVELEVBQUEsR0FBRyxPQUFPLENBQUMsSUFBbEUsQ0FBTixDQUFBO0FBQUEsSUFDQSxHQUFHLENBQUMsY0FBSixDQUFtQixJQUFuQixFQUF5QixJQUF6QixFQUErQixFQUFBLEdBQUcsT0FBTyxDQUFDLEVBQTFDLENBREEsQ0FBQTtBQUdBLElBQUEsSUFBRyxHQUFBLEtBQU8sVUFBUCxJQUFxQixNQUF4QjtBQUNDO0FBQUEsV0FBQSxxQ0FBQTt1QkFBQTtBQUNDLFFBQUEsSUFBRyxNQUFBLENBQUEsS0FBQSxLQUFpQixRQUFwQjtBQUNDLFVBQUEsS0FBQSxHQUFRLElBQUMsQ0FBQyxHQUFHLENBQUMsY0FBTixDQUFxQixFQUFBLEdBQUcsS0FBeEIsQ0FBUixDQUREO1NBQUE7QUFBQSxRQUVBLEdBQUcsQ0FBQyxXQUFKLENBQWdCLEtBQWhCLENBRkEsQ0FERDtBQUFBLE9BREQ7S0FIQTtBQUFBLElBU0EsSUFBQSxHQUFPLElBQUMsQ0FBQyxHQUFHLENBQUMsb0JBQU4sQ0FBMkIsTUFBM0IsQ0FBbUMsQ0FBQSxDQUFBLENBVDFDLENBQUE7QUFBQSxJQVVBLElBQUksQ0FBQyxXQUFMLENBQWlCLEdBQWpCLENBVkEsQ0FBQTtBQVlBLElBQUEsSUFBRyxPQUFPLENBQUMsSUFBUixLQUFnQixVQUFuQjthQUFtQyxJQUFDLENBQUEsU0FBVSxDQUFBLEVBQUEsR0FBRyxPQUFPLENBQUMsRUFBWCxDQUFYLEdBQThCLElBQWpFO0tBQUEsTUFBQTthQUEwRSxJQUFDLENBQUEsS0FBTSxDQUFBLEVBQUEsR0FBRyxPQUFPLENBQUMsRUFBWCxDQUFQLEdBQTBCLElBQXBHO0tBYk87RUFBQSxDQXZCUixDQUFBOztBQUFBLHFCQXNDQSxRQUFBLEdBQVUsU0FBQyxRQUFELEVBQVcsR0FBWCxFQUFnQixXQUFoQixHQUFBO0FBQ1QsUUFBQSx3QkFBQTtBQUFBLElBQUEsSUFBRyxNQUFBLENBQUEsR0FBQSxLQUFlLFFBQWxCO0FBQ0MsTUFBQSxHQUFBLEdBQU0sSUFBQyxDQUFDLEdBQUcsQ0FBQyxjQUFOLENBQXFCLEVBQUEsR0FBRyxHQUF4QixDQUFOLENBREQ7S0FBQTtBQUdBLElBQUEsSUFBRyxDQUFBLEtBQU0sQ0FBQyxPQUFOLENBQWMsUUFBZCxDQUFKO0FBQ0MsTUFBQSxPQUFBLEdBQVUsUUFBVixDQUFBO0FBQ0EsTUFBQSxJQUFHLE1BQUEsQ0FBQSxPQUFBLEtBQW1CLFFBQXRCO0FBQ0MsUUFBQSxPQUFBLEdBQVUsSUFBQyxDQUFDLEdBQUcsQ0FBQyxjQUFOLENBQXFCLEVBQUEsR0FBRyxPQUF4QixDQUFWLENBREQ7T0FEQTtBQUlBLE1BQUEsSUFBRyxDQUFBLFdBQUg7ZUFDQyxHQUFHLENBQUMsV0FBSixDQUFnQixHQUFoQixFQUREO09BQUEsTUFBQTtlQUdDLEdBQUcsQ0FBQyxZQUFKLENBQWlCLE9BQWpCLEVBQTBCLFdBQTFCLEVBSEQ7T0FMRDtLQUFBLE1BQUE7QUFXQztXQUFBLDBDQUFBOzhCQUFBO0FBQ0MsUUFBQSxJQUFHLE1BQUEsQ0FBQSxPQUFBLEtBQW1CLFFBQXRCO0FBQ0MsVUFBQSxPQUFBLEdBQVUsSUFBQyxDQUFDLEdBQUcsQ0FBQyxjQUFOLENBQXFCLEVBQUEsR0FBRyxPQUF4QixDQUFWLENBREQ7U0FBQTtBQUdBLFFBQUEsSUFBRyxDQUFBLFdBQUg7dUJBQ0MsR0FBRyxDQUFDLFdBQUosQ0FBZ0IsT0FBaEIsR0FERDtTQUFBLE1BQUE7dUJBR0MsR0FBRyxDQUFDLFlBQUosQ0FBaUIsT0FBakIsRUFBMEIsV0FBMUIsR0FIRDtTQUpEO0FBQUE7cUJBWEQ7S0FKUztFQUFBLENBdENWLENBQUE7O0FBQUEscUJBOERBLElBQUEsR0FBTSxTQUFDLEtBQUQsRUFBUSxJQUFSLEdBQUE7QUFDTCxJQUFBLElBQUcsTUFBQSxDQUFBLEtBQUEsS0FBaUIsUUFBcEI7QUFDQyxNQUFBLEtBQUEsR0FBUSxJQUFDLENBQUMsR0FBRyxDQUFDLGNBQU4sQ0FBcUIsRUFBQSxHQUFHLEtBQXhCLENBQVIsQ0FERDtLQUFBO0FBR0EsSUFBQSxJQUFHLE1BQUEsQ0FBQSxJQUFBLEtBQWtCLFFBQXJCO0FBQ0MsTUFBQSxJQUFBLEdBQU8sSUFBSSxDQUFDLGNBQUwsQ0FBb0IsSUFBcEIsRUFBMEIsSUFBMUIsQ0FBUCxDQUREO0tBSEE7V0FNQSxLQUFLLENBQUMsY0FBTixDQUFxQixJQUFyQixFQUEyQixNQUEzQixFQUFtQyxPQUFBLEdBQVEsSUFBUixHQUFhLEdBQWhELEVBUEs7RUFBQSxDQTlETixDQUFBOztrQkFBQTs7R0FEOEIsTUFBL0IsQ0FBQTs7Ozs7QUNBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTs7QUN4R0EsT0FBTyxDQUFDLEtBQVIsR0FBZ0IsWUFBaEIsQ0FBQTs7QUFBQSxPQUVPLENBQUMsVUFBUixHQUFxQixTQUFBLEdBQUE7U0FDcEIsS0FBQSxDQUFNLHVCQUFOLEVBRG9CO0FBQUEsQ0FGckIsQ0FBQTs7QUFBQSxPQUtPLENBQUMsT0FBUixHQUFrQixDQUFDLENBQUQsRUFBSSxDQUFKLEVBQU8sQ0FBUCxDQUxsQixDQUFBIiwiZmlsZSI6ImdlbmVyYXRlZC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzQ29udGVudCI6WyIoZnVuY3Rpb24gZSh0LG4scil7ZnVuY3Rpb24gcyhvLHUpe2lmKCFuW29dKXtpZighdFtvXSl7dmFyIGE9dHlwZW9mIHJlcXVpcmU9PVwiZnVuY3Rpb25cIiYmcmVxdWlyZTtpZighdSYmYSlyZXR1cm4gYShvLCEwKTtpZihpKXJldHVybiBpKG8sITApO3ZhciBmPW5ldyBFcnJvcihcIkNhbm5vdCBmaW5kIG1vZHVsZSAnXCIrbytcIidcIik7dGhyb3cgZi5jb2RlPVwiTU9EVUxFX05PVF9GT1VORFwiLGZ9dmFyIGw9bltvXT17ZXhwb3J0czp7fX07dFtvXVswXS5jYWxsKGwuZXhwb3J0cyxmdW5jdGlvbihlKXt2YXIgbj10W29dWzFdW2VdO3JldHVybiBzKG4/bjplKX0sbCxsLmV4cG9ydHMsZSx0LG4scil9cmV0dXJuIG5bb10uZXhwb3J0c312YXIgaT10eXBlb2YgcmVxdWlyZT09XCJmdW5jdGlvblwiJiZyZXF1aXJlO2Zvcih2YXIgbz0wO288ci5sZW5ndGg7bysrKXMocltvXSk7cmV0dXJuIHN9KSIsImNsYXNzIGV4cG9ydHMuTGF5ZXJTVkcgZXh0ZW5kcyBMYXllciBcblx0Y29uc3RydWN0b3I6IChvcHRpb25zPXt9KSAtPlxuXHRcdFxuXHRcdHN1cGVyIG9wdGlvbnNcblxuXHRcdEBodG1sID0gXCI8c3ZnIGlkPScje29wdGlvbnMuaWR9JyB3aWR0aD0nI3tALndpZHRofScgaGVpZ2h0PScje0AuaGVpZ2h0fSc+PGRlZnM+PC9kZWZzPjwvc3ZnPlwiXG5cdFx0QHN2ZyA9IEAucXVlcnlTZWxlY3RvcihcIiMje29wdGlvbnMuaWR9XCIpXHRcblxuXHRcdEBzaGFwZXMgPSB7fVxuXHRcdEBtYXNrcyA9IHt9XG5cdFx0QGNsaXBQYXRocyA9IHt9XG5cblx0YWRkU2hhcGU6IChvcHRpb25zPXt9KSAtPlxuXHRcdHNoYXBlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudE5TKFwiaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmdcIiwgXCIje29wdGlvbnMuc2hhcGV9XCIpIFxuXG5cdFx0Zm9yIG93biBvcHRpb24sIHZhbHVlIG9mIG9wdGlvbnNcblx0XHRcdFx0aWYgb3B0aW9uIGlzbnQgXCJzaGFwZVwiXG5cdFx0XHRcdFx0c2hhcGUuc2V0QXR0cmlidXRlTlMobnVsbCwgXCIje29wdGlvbn1cIiwgXCIje29wdGlvbnNbb3B0aW9uXX1cIilcblxuXHRcdEBzdmcuYXBwZW5kQ2hpbGQoc2hhcGUpXG5cdFx0QHNoYXBlc1tcIiN7b3B0aW9ucy5pZH1cIl0gPSBzaGFwZVxuXG5cdFx0cmV0dXJuIHNoYXBlXG5cblx0YWRkRGVmOiAob3B0aW9ucz17fSkgLT5cblx0XHRkZWYgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50TlMoXCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiLCBcIiN7b3B0aW9ucy50eXBlfVwiKVxuXHRcdGRlZi5zZXRBdHRyaWJ1dGVOUyhudWxsLCBcImlkXCIsIFwiI3tvcHRpb25zLmlkfVwiKVxuXG5cdFx0aWYgZGVmIGlzIFwiY2xpcFBhdGhcIiBvciBcIm1hc2tcIlxuXHRcdFx0Zm9yIHNoYXBlIGluIG9wdGlvbnMuc2hhcGVzXG5cdFx0XHRcdGlmIHR5cGVvZihzaGFwZSkgaXMgXCJzdHJpbmdcIlxuXHRcdFx0XHRcdHNoYXBlID0gQC5zdmcuZ2V0RWxlbWVudEJ5SWQoXCIje3NoYXBlfVwiKVxuXHRcdFx0XHRkZWYuYXBwZW5kQ2hpbGQoc2hhcGUpXG5cblx0XHRkZWZzID0gQC5zdmcuZ2V0RWxlbWVudHNCeVRhZ05hbWUoXCJkZWZzXCIpWzBdXG5cdFx0ZGVmcy5hcHBlbmRDaGlsZChkZWYpXG5cblx0XHRpZiBvcHRpb25zLnR5cGUgaXMgXCJjbGlwUGF0aFwiIHRoZW4gQGNsaXBQYXRoc1tcIiN7b3B0aW9ucy5pZH1cIl0gPSBkZWYgZWxzZSBAbWFza3NbXCIje29wdGlvbnMuaWR9XCJdID0gZGVmXG5cblx0YWRkVG9EZWY6IChlbGVtZW50cywgZGVmLCBwcmV2RWxlbWVudCkgLT5cblx0XHRpZiB0eXBlb2YoZGVmKSBpcyBcInN0cmluZ1wiXG5cdFx0XHRkZWYgPSBALnN2Zy5nZXRFbGVtZW50QnlJZChcIiN7ZGVmfVwiKVxuXG5cdFx0aWYgIUFycmF5LmlzQXJyYXkoZWxlbWVudHMpXG5cdFx0XHRlbGVtZW50ID0gZWxlbWVudHNcblx0XHRcdGlmIHR5cGVvZihlbGVtZW50KSBpcyBcInN0cmluZ1wiXG5cdFx0XHRcdGVsZW1lbnQgPSBALnN2Zy5nZXRFbGVtZW50QnlJZChcIiN7ZWxlbWVudH1cIilcblxuXHRcdFx0aWYgIXByZXZFbGVtZW50XG5cdFx0XHRcdGRlZi5hcHBlbmRDaGlsZChlbGUpXG5cdFx0XHRlbHNlXG5cdFx0XHRcdGRlZi5pbnNlcnRCZWZvcmUoZWxlbWVudCwgcHJldkVsZW1lbnQpXG5cblx0XHRlbHNlXG5cdFx0XHRmb3IgZWxlbWVudCBpbiBlbGVtZW50c1xuXHRcdFx0XHRpZiB0eXBlb2YoZWxlbWVudCkgaXMgXCJzdHJpbmdcIlxuXHRcdFx0XHRcdGVsZW1lbnQgPSBALnN2Zy5nZXRFbGVtZW50QnlJZChcIiN7ZWxlbWVudH1cIilcblxuXHRcdFx0XHRpZiAhcHJldkVsZW1lbnRcblx0XHRcdFx0XHRkZWYuYXBwZW5kQ2hpbGQoZWxlbWVudClcblx0XHRcdFx0ZWxzZVxuXHRcdFx0XHRcdGRlZi5pbnNlcnRCZWZvcmUoZWxlbWVudCwgcHJldkVsZW1lbnQpXG5cblx0bWFzazogKHNoYXBlLCBtYXNrKSAtPlxuXHRcdGlmIHR5cGVvZihzaGFwZSkgaXMgXCJzdHJpbmdcIlxuXHRcdFx0c2hhcGUgPSBALnN2Zy5nZXRFbGVtZW50QnlJZChcIiN7c2hhcGV9XCIpXG5cblx0XHRpZiB0eXBlb2YobWFzaykgaXNudCBcInN0cmluZ1wiXG5cdFx0XHRtYXNrID0gbWFzay5nZXRBdHRyaWJ1dGVOUyhudWxsLCBcImlkXCIpXG5cblx0XHRzaGFwZS5zZXRBdHRyaWJ1dGVOUyhudWxsLCBcIm1hc2tcIiwgXCJ1cmwoIyN7bWFza30pXCIpIiwiLy8gR2VuZXJhdGVkIGJ5IENvZmZlZVNjcmlwdCAxLjkuMVxudmFyIGV4dGVuZCA9IGZ1bmN0aW9uKGNoaWxkLCBwYXJlbnQpIHsgZm9yICh2YXIga2V5IGluIHBhcmVudCkgeyBpZiAoaGFzUHJvcC5jYWxsKHBhcmVudCwga2V5KSkgY2hpbGRba2V5XSA9IHBhcmVudFtrZXldOyB9IGZ1bmN0aW9uIGN0b3IoKSB7IHRoaXMuY29uc3RydWN0b3IgPSBjaGlsZDsgfSBjdG9yLnByb3RvdHlwZSA9IHBhcmVudC5wcm90b3R5cGU7IGNoaWxkLnByb3RvdHlwZSA9IG5ldyBjdG9yKCk7IGNoaWxkLl9fc3VwZXJfXyA9IHBhcmVudC5wcm90b3R5cGU7IHJldHVybiBjaGlsZDsgfSxcbiAgaGFzUHJvcCA9IHt9Lmhhc093blByb3BlcnR5O1xuXG5leHBvcnRzLkxheWVyU1ZHID0gKGZ1bmN0aW9uKHN1cGVyQ2xhc3MpIHtcbiAgZXh0ZW5kKExheWVyU1ZHLCBzdXBlckNsYXNzKTtcblxuICBmdW5jdGlvbiBMYXllclNWRyhvcHRpb25zKSB7XG4gICAgaWYgKG9wdGlvbnMgPT0gbnVsbCkge1xuICAgICAgb3B0aW9ucyA9IHt9O1xuICAgIH1cbiAgICBMYXllclNWRy5fX3N1cGVyX18uY29uc3RydWN0b3IuY2FsbCh0aGlzLCBvcHRpb25zKTtcbiAgICB0aGlzLmh0bWwgPSBcIjxzdmcgaWQ9J1wiICsgb3B0aW9ucy5pZCArIFwiJyB3aWR0aD0nXCIgKyB0aGlzLndpZHRoICsgXCInIGhlaWdodD0nXCIgKyB0aGlzLmhlaWdodCArIFwiJz48ZGVmcz48L2RlZnM+PC9zdmc+XCI7XG4gICAgdGhpcy5zdmcgPSB0aGlzLnF1ZXJ5U2VsZWN0b3IoXCIjXCIgKyBvcHRpb25zLmlkKTtcbiAgICB0aGlzLnNoYXBlcyA9IHt9O1xuICAgIHRoaXMubWFza3MgPSB7fTtcbiAgICB0aGlzLmNsaXBQYXRocyA9IHt9O1xuICB9XG5cbiAgTGF5ZXJTVkcucHJvdG90eXBlLmFkZFNoYXBlID0gZnVuY3Rpb24ob3B0aW9ucykge1xuICAgIHZhciBvcHRpb24sIHNoYXBlLCB2YWx1ZTtcbiAgICBpZiAob3B0aW9ucyA9PSBudWxsKSB7XG4gICAgICBvcHRpb25zID0ge307XG4gICAgfVxuICAgIHNoYXBlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudE5TKFwiaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmdcIiwgXCJcIiArIG9wdGlvbnMuc2hhcGUpO1xuICAgIGZvciAob3B0aW9uIGluIG9wdGlvbnMpIHtcbiAgICAgIGlmICghaGFzUHJvcC5jYWxsKG9wdGlvbnMsIG9wdGlvbikpIGNvbnRpbnVlO1xuICAgICAgdmFsdWUgPSBvcHRpb25zW29wdGlvbl07XG4gICAgICBpZiAob3B0aW9uICE9PSBcInNoYXBlXCIpIHtcbiAgICAgICAgc2hhcGUuc2V0QXR0cmlidXRlTlMobnVsbCwgXCJcIiArIG9wdGlvbiwgXCJcIiArIG9wdGlvbnNbb3B0aW9uXSk7XG4gICAgICB9XG4gICAgfVxuICAgIHRoaXMuc3ZnLmFwcGVuZENoaWxkKHNoYXBlKTtcbiAgICB0aGlzLnNoYXBlc1tcIlwiICsgb3B0aW9ucy5pZF0gPSBzaGFwZTtcbiAgICByZXR1cm4gc2hhcGU7XG4gIH07XG5cbiAgTGF5ZXJTVkcucHJvdG90eXBlLmFkZERlZiA9IGZ1bmN0aW9uKG9wdGlvbnMpIHtcbiAgICB2YXIgZGVmLCBkZWZzLCBpLCBsZW4sIHJlZiwgc2hhcGU7XG4gICAgaWYgKG9wdGlvbnMgPT0gbnVsbCkge1xuICAgICAgb3B0aW9ucyA9IHt9O1xuICAgIH1cbiAgICBkZWYgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50TlMoXCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiLCBcIlwiICsgb3B0aW9ucy50eXBlKTtcbiAgICBkZWYuc2V0QXR0cmlidXRlTlMobnVsbCwgXCJpZFwiLCBcIlwiICsgb3B0aW9ucy5pZCk7XG4gICAgaWYgKGRlZiA9PT0gXCJjbGlwUGF0aFwiIHx8IFwibWFza1wiKSB7XG4gICAgICByZWYgPSBvcHRpb25zLnNoYXBlcztcbiAgICAgIGZvciAoaSA9IDAsIGxlbiA9IHJlZi5sZW5ndGg7IGkgPCBsZW47IGkrKykge1xuICAgICAgICBzaGFwZSA9IHJlZltpXTtcbiAgICAgICAgaWYgKHR5cGVvZiBzaGFwZSA9PT0gXCJzdHJpbmdcIikge1xuICAgICAgICAgIHNoYXBlID0gdGhpcy5zdmcuZ2V0RWxlbWVudEJ5SWQoXCJcIiArIHNoYXBlKTtcbiAgICAgICAgfVxuICAgICAgICBkZWYuYXBwZW5kQ2hpbGQoc2hhcGUpO1xuICAgICAgfVxuICAgIH1cbiAgICBkZWZzID0gdGhpcy5zdmcuZ2V0RWxlbWVudHNCeVRhZ05hbWUoXCJkZWZzXCIpWzBdO1xuICAgIGRlZnMuYXBwZW5kQ2hpbGQoZGVmKTtcbiAgICBpZiAob3B0aW9ucy50eXBlID09PSBcImNsaXBQYXRoXCIpIHtcbiAgICAgIHJldHVybiB0aGlzLmNsaXBQYXRoc1tcIlwiICsgb3B0aW9ucy5pZF0gPSBkZWY7XG4gICAgfSBlbHNlIHtcbiAgICAgIHJldHVybiB0aGlzLm1hc2tzW1wiXCIgKyBvcHRpb25zLmlkXSA9IGRlZjtcbiAgICB9XG4gIH07XG5cbiAgTGF5ZXJTVkcucHJvdG90eXBlLmFkZFRvRGVmID0gZnVuY3Rpb24oZWxlbWVudHMsIGRlZiwgcHJldkVsZW1lbnQpIHtcbiAgICB2YXIgZWxlbWVudCwgaSwgbGVuLCByZXN1bHRzO1xuICAgIGlmICh0eXBlb2YgZGVmID09PSBcInN0cmluZ1wiKSB7XG4gICAgICBkZWYgPSB0aGlzLnN2Zy5nZXRFbGVtZW50QnlJZChcIlwiICsgZGVmKTtcbiAgICB9XG4gICAgaWYgKCFBcnJheS5pc0FycmF5KGVsZW1lbnRzKSkge1xuICAgICAgZWxlbWVudCA9IGVsZW1lbnRzO1xuICAgICAgaWYgKHR5cGVvZiBlbGVtZW50ID09PSBcInN0cmluZ1wiKSB7XG4gICAgICAgIGVsZW1lbnQgPSB0aGlzLnN2Zy5nZXRFbGVtZW50QnlJZChcIlwiICsgZWxlbWVudCk7XG4gICAgICB9XG4gICAgICBpZiAoIXByZXZFbGVtZW50KSB7XG4gICAgICAgIHJldHVybiBkZWYuYXBwZW5kQ2hpbGQoZWxlKTtcbiAgICAgIH0gZWxzZSB7XG4gICAgICAgIHJldHVybiBkZWYuaW5zZXJ0QmVmb3JlKGVsZW1lbnQsIHByZXZFbGVtZW50KTtcbiAgICAgIH1cbiAgICB9IGVsc2Uge1xuICAgICAgcmVzdWx0cyA9IFtdO1xuICAgICAgZm9yIChpID0gMCwgbGVuID0gZWxlbWVudHMubGVuZ3RoOyBpIDwgbGVuOyBpKyspIHtcbiAgICAgICAgZWxlbWVudCA9IGVsZW1lbnRzW2ldO1xuICAgICAgICBpZiAodHlwZW9mIGVsZW1lbnQgPT09IFwic3RyaW5nXCIpIHtcbiAgICAgICAgICBlbGVtZW50ID0gdGhpcy5zdmcuZ2V0RWxlbWVudEJ5SWQoXCJcIiArIGVsZW1lbnQpO1xuICAgICAgICB9XG4gICAgICAgIGlmICghcHJldkVsZW1lbnQpIHtcbiAgICAgICAgICByZXN1bHRzLnB1c2goZGVmLmFwcGVuZENoaWxkKGVsZW1lbnQpKTtcbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICByZXN1bHRzLnB1c2goZGVmLmluc2VydEJlZm9yZShlbGVtZW50LCBwcmV2RWxlbWVudCkpO1xuICAgICAgICB9XG4gICAgICB9XG4gICAgICByZXR1cm4gcmVzdWx0cztcbiAgICB9XG4gIH07XG5cbiAgTGF5ZXJTVkcucHJvdG90eXBlLm1hc2sgPSBmdW5jdGlvbihzaGFwZSwgbWFzaykge1xuICAgIGlmICh0eXBlb2Ygc2hhcGUgPT09IFwic3RyaW5nXCIpIHtcbiAgICAgIHNoYXBlID0gdGhpcy5zdmcuZ2V0RWxlbWVudEJ5SWQoXCJcIiArIHNoYXBlKTtcbiAgICB9XG4gICAgaWYgKHR5cGVvZiBtYXNrICE9PSBcInN0cmluZ1wiKSB7XG4gICAgICBtYXNrID0gbWFzay5nZXRBdHRyaWJ1dGVOUyhudWxsLCBcImlkXCIpO1xuICAgIH1cbiAgICByZXR1cm4gc2hhcGUuc2V0QXR0cmlidXRlTlMobnVsbCwgXCJtYXNrXCIsIFwidXJsKCNcIiArIG1hc2sgKyBcIilcIik7XG4gIH07XG5cbiAgcmV0dXJuIExheWVyU1ZHO1xuXG59KShMYXllcik7XG4iLCIjIEFkZCB0aGUgZm9sbG93aW5nIGxpbmUgdG8geW91ciBwcm9qZWN0IGluIEZyYW1lciBTdHVkaW8uIFxuIyBteU1vZHVsZSA9IHJlcXVpcmUgXCJteU1vZHVsZVwiXG4jIFJlZmVyZW5jZSB0aGUgY29udGVudHMgYnkgbmFtZSwgbGlrZSBteU1vZHVsZS5teUZ1bmN0aW9uKCkgb3IgbXlNb2R1bGUubXlWYXJcblxuZXhwb3J0cy5teVZhciA9IFwibXlWYXJpYWJsZVwiXG5cbmV4cG9ydHMubXlGdW5jdGlvbiA9IC0+XG5cdHByaW50IFwibXlGdW5jdGlvbiBpcyBydW5uaW5nXCJcblxuZXhwb3J0cy5teUFycmF5ID0gWzEsIDIsIDNdIl19
