require=(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({"LayerSVG":[function(require,module,exports){
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

exports.LayerSVG = (function(superClass) {
  extend(LayerSVG, superClass);

  function LayerSVG(options) {
    if (options == null) {
      options = {};
    }
    LayerSVG.__super__.constructor.call(this, options);
    this.shapes = {};
    this.masks = {};
    this.html = "<svg id='" + options.id + "' width='" + this.width + "' height='" + this.height + "'><defs></defs></svg>";
    this.svg = this.querySelector("#" + options.id);
  }

  LayerSVG.prototype.addShape = function(type, options) {
    var option, shape, value;
    if (options == null) {
      options = {};
    }
    shape = document.createElementNS("http://www.w3.org/2000/svg", "" + type);
    for (option in options) {
      if (!hasProp.call(options, option)) continue;
      value = options[option];
      shape.setAttributeNS(null, "" + option, "" + options[option]);
    }
    this.svg.appendChild(shape);
    this.shapes["" + options.id] = shape;
    return shape;
  };

  LayerSVG.prototype.addMask = function(id) {
    var defs, mask;
    mask = document.createElementNS("http://www.w3.org/2000/svg", "mask");
    mask.setAttributeNS(null, "id", "" + id);
    defs = this.svg.getElementsByTagName("defs")[0];
    return defs.appendChild(mask);
  };

  LayerSVG.prototype.addToMask = function(element, id) {
    var mask;
    mask = this.svg.getElementById("" + id);
    return mask.appendChild(element);
  };

  LayerSVG.prototype.setMask = function(element, id) {
    if (typeof id !== "string") {
      id = id.getAttributeNS(null, "id");
    }
    return element.setAttributeNS(null, "mask", "url(#" + id + ")");
  };

  return LayerSVG;

})(Layer);



},{}],"LayerSVG":[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

exports.LayerSVG = (function(superClass) {
  extend(LayerSVG, superClass);

  function LayerSVG(options) {
    if (options == null) {
      options = {};
    }
    LayerSVG.__super__.constructor.call(this, options);
    this.shapes = {};
    this.masks = {};
    this.html = "<svg id='" + options.id + "' width='" + this.width + "' height='" + this.height + "'><defs></defs></svg>";
    this.svg = this.querySelector("#" + options.id);
  }

  LayerSVG.prototype.addShape = function(type, options) {
    var option, shape, value;
    if (options == null) {
      options = {};
    }
    shape = document.createElementNS("http://www.w3.org/2000/svg", "" + type);
    for (option in options) {
      if (!hasProp.call(options, option)) continue;
      value = options[option];
      shape.setAttributeNS(null, "" + option, "" + options[option]);
    }
    this.svg.appendChild(shape);
    this.shapes["" + options.id] = shape;
    return shape;
  };

  LayerSVG.prototype.addMask = function(id) {
    var defs, mask;
    mask = document.createElementNS("http://www.w3.org/2000/svg", "mask");
    mask.setAttributeNS(null, "id", "" + id);
    defs = this.svg.getElementsByTagName("defs")[0];
    return defs.appendChild(mask);
  };

  LayerSVG.prototype.addToMask = function(element, id) {
    var mask;
    mask = this.svg.getElementById("" + id);
    return mask.appendChild(element);
  };

  LayerSVG.prototype.setMask = function(element, id) {
    if (typeof id !== "string") {
      id = id.getAttributeNS(null, "id");
    }
    return element.setAttributeNS(null, "mask", "url(#" + id + ")");
  };

  return LayerSVG;

})(Layer);

},{}],"myModule":[function(require,module,exports){
exports.myVar = "myVariable";

exports.myFunction = function() {
  return print("myFunction is running");
};

exports.myArray = [1, 2, 3];



},{}]},{},[])
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5vZGVfbW9kdWxlcy9icm93c2VyaWZ5L25vZGVfbW9kdWxlcy9icm93c2VyLXBhY2svX3ByZWx1ZGUuanMiLCIvVXNlcnMvam9zaG10dWNrZXIvR2l0SHViL0xheWVyU1ZHL0xheWVyU1ZHLmZyYW1lci9tb2R1bGVzL0xheWVyU1ZHLmNvZmZlZSIsIi4uLy4uLy4uLy4uLy4uL1VzZXJzL2pvc2htdHVja2VyL0dpdEh1Yi9MYXllclNWRy9MYXllclNWRy5mcmFtZXIvbW9kdWxlcy9MYXllclNWRy5qcyIsIi9Vc2Vycy9qb3NobXR1Y2tlci9HaXRIdWIvTGF5ZXJTVkcvTGF5ZXJTVkcuZnJhbWVyL21vZHVsZXMvbXlNb2R1bGUuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0FDQUEsSUFBQTs2QkFBQTs7QUFBQSxPQUFhLENBQUM7QUFDYiw4QkFBQSxDQUFBOztBQUFhLEVBQUEsa0JBQUMsT0FBRCxHQUFBOztNQUFDLFVBQVE7S0FFckI7QUFBQSxJQUFBLDBDQUFNLE9BQU4sQ0FBQSxDQUFBO0FBQUEsSUFFQSxJQUFDLENBQUEsTUFBRCxHQUFVLEVBRlYsQ0FBQTtBQUFBLElBR0EsSUFBQyxDQUFBLEtBQUQsR0FBUyxFQUhULENBQUE7QUFBQSxJQUlBLElBQUMsQ0FBQSxJQUFELEdBQVEsV0FBQSxHQUFZLE9BQU8sQ0FBQyxFQUFwQixHQUF1QixXQUF2QixHQUFrQyxJQUFDLENBQUMsS0FBcEMsR0FBMEMsWUFBMUMsR0FBc0QsSUFBQyxDQUFDLE1BQXhELEdBQStELHVCQUp2RSxDQUFBO0FBQUEsSUFLQSxJQUFDLENBQUEsR0FBRCxHQUFPLElBQUMsQ0FBQyxhQUFGLENBQWdCLEdBQUEsR0FBSSxPQUFPLENBQUMsRUFBNUIsQ0FMUCxDQUZZO0VBQUEsQ0FBYjs7QUFBQSxxQkFVQSxRQUFBLEdBQVUsU0FBQyxJQUFELEVBQU8sT0FBUCxHQUFBO0FBQ1QsUUFBQSxvQkFBQTs7TUFEZ0IsVUFBUTtLQUN4QjtBQUFBLElBQUEsS0FBQSxHQUFRLFFBQVEsQ0FBQyxlQUFULENBQXlCLDRCQUF6QixFQUF1RCxFQUFBLEdBQUcsSUFBMUQsQ0FBUixDQUFBO0FBQ0EsU0FBQSxpQkFBQTs7OEJBQUE7QUFDQyxNQUFBLEtBQUssQ0FBQyxjQUFOLENBQXFCLElBQXJCLEVBQTJCLEVBQUEsR0FBRyxNQUE5QixFQUF3QyxFQUFBLEdBQUcsT0FBUSxDQUFBLE1BQUEsQ0FBbkQsQ0FBQSxDQUREO0FBQUEsS0FEQTtBQUFBLElBSUEsSUFBQyxDQUFBLEdBQUcsQ0FBQyxXQUFMLENBQWlCLEtBQWpCLENBSkEsQ0FBQTtBQUFBLElBS0EsSUFBQyxDQUFBLE1BQU8sQ0FBQSxFQUFBLEdBQUcsT0FBTyxDQUFDLEVBQVgsQ0FBUixHQUEyQixLQUwzQixDQUFBO0FBT0EsV0FBTyxLQUFQLENBUlM7RUFBQSxDQVZWLENBQUE7O0FBQUEscUJBb0JBLE9BQUEsR0FBUyxTQUFDLEVBQUQsR0FBQTtBQUNSLFFBQUEsVUFBQTtBQUFBLElBQUEsSUFBQSxHQUFPLFFBQVEsQ0FBQyxlQUFULENBQXlCLDRCQUF6QixFQUF1RCxNQUF2RCxDQUFQLENBQUE7QUFBQSxJQUNBLElBQUksQ0FBQyxjQUFMLENBQW9CLElBQXBCLEVBQTBCLElBQTFCLEVBQWdDLEVBQUEsR0FBRyxFQUFuQyxDQURBLENBQUE7QUFBQSxJQUdBLElBQUEsR0FBTyxJQUFDLENBQUMsR0FBRyxDQUFDLG9CQUFOLENBQTJCLE1BQTNCLENBQW1DLENBQUEsQ0FBQSxDQUgxQyxDQUFBO1dBSUEsSUFBSSxDQUFDLFdBQUwsQ0FBaUIsSUFBakIsRUFMUTtFQUFBLENBcEJULENBQUE7O0FBQUEscUJBMkJBLFNBQUEsR0FBVyxTQUFDLE9BQUQsRUFBVSxFQUFWLEdBQUE7QUFDVixRQUFBLElBQUE7QUFBQSxJQUFBLElBQUEsR0FBTyxJQUFDLENBQUMsR0FBRyxDQUFDLGNBQU4sQ0FBcUIsRUFBQSxHQUFHLEVBQXhCLENBQVAsQ0FBQTtXQUNBLElBQUksQ0FBQyxXQUFMLENBQWlCLE9BQWpCLEVBRlU7RUFBQSxDQTNCWCxDQUFBOztBQUFBLHFCQStCQSxPQUFBLEdBQVMsU0FBQyxPQUFELEVBQVUsRUFBVixHQUFBO0FBQ1IsSUFBQSxJQUFHLE1BQUEsQ0FBQSxFQUFBLEtBQWdCLFFBQW5CO0FBQ0MsTUFBQSxFQUFBLEdBQUssRUFBRSxDQUFDLGNBQUgsQ0FBa0IsSUFBbEIsRUFBd0IsSUFBeEIsQ0FBTCxDQUREO0tBQUE7V0FHQSxPQUFPLENBQUMsY0FBUixDQUF1QixJQUF2QixFQUE2QixNQUE3QixFQUFxQyxPQUFBLEdBQVEsRUFBUixHQUFXLEdBQWhELEVBSlE7RUFBQSxDQS9CVCxDQUFBOztrQkFBQTs7R0FEOEIsTUFBL0IsQ0FBQTs7Ozs7QUNBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBOztBQ3REQSxPQUFPLENBQUMsS0FBUixHQUFnQixZQUFoQixDQUFBOztBQUFBLE9BRU8sQ0FBQyxVQUFSLEdBQXFCLFNBQUEsR0FBQTtTQUNwQixLQUFBLENBQU0sdUJBQU4sRUFEb0I7QUFBQSxDQUZyQixDQUFBOztBQUFBLE9BS08sQ0FBQyxPQUFSLEdBQWtCLENBQUMsQ0FBRCxFQUFJLENBQUosRUFBTyxDQUFQLENBTGxCLENBQUEiLCJmaWxlIjoiZ2VuZXJhdGVkLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXNDb250ZW50IjpbIihmdW5jdGlvbiBlKHQsbixyKXtmdW5jdGlvbiBzKG8sdSl7aWYoIW5bb10pe2lmKCF0W29dKXt2YXIgYT10eXBlb2YgcmVxdWlyZT09XCJmdW5jdGlvblwiJiZyZXF1aXJlO2lmKCF1JiZhKXJldHVybiBhKG8sITApO2lmKGkpcmV0dXJuIGkobywhMCk7dmFyIGY9bmV3IEVycm9yKFwiQ2Fubm90IGZpbmQgbW9kdWxlICdcIitvK1wiJ1wiKTt0aHJvdyBmLmNvZGU9XCJNT0RVTEVfTk9UX0ZPVU5EXCIsZn12YXIgbD1uW29dPXtleHBvcnRzOnt9fTt0W29dWzBdLmNhbGwobC5leHBvcnRzLGZ1bmN0aW9uKGUpe3ZhciBuPXRbb11bMV1bZV07cmV0dXJuIHMobj9uOmUpfSxsLGwuZXhwb3J0cyxlLHQsbixyKX1yZXR1cm4gbltvXS5leHBvcnRzfXZhciBpPXR5cGVvZiByZXF1aXJlPT1cImZ1bmN0aW9uXCImJnJlcXVpcmU7Zm9yKHZhciBvPTA7bzxyLmxlbmd0aDtvKyspcyhyW29dKTtyZXR1cm4gc30pIiwiY2xhc3MgZXhwb3J0cy5MYXllclNWRyBleHRlbmRzIExheWVyIFxuXHRjb25zdHJ1Y3RvcjogKG9wdGlvbnM9e30pIC0+XG5cdFx0XG5cdFx0c3VwZXIgb3B0aW9uc1xuXG5cdFx0QHNoYXBlcyA9IHt9XG5cdFx0QG1hc2tzID0ge31cblx0XHRAaHRtbCA9IFwiPHN2ZyBpZD0nI3tvcHRpb25zLmlkfScgd2lkdGg9JyN7QC53aWR0aH0nIGhlaWdodD0nI3tALmhlaWdodH0nPjxkZWZzPjwvZGVmcz48L3N2Zz5cIlxuXHRcdEBzdmcgPSBALnF1ZXJ5U2VsZWN0b3IoXCIjI3tvcHRpb25zLmlkfVwiKVx0XG5cblxuXHRhZGRTaGFwZTogKHR5cGUsIG9wdGlvbnM9e30pIC0+XG5cdFx0c2hhcGUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50TlMoXCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiLCBcIiN7dHlwZX1cIilcblx0XHRmb3Igb3duIG9wdGlvbiwgdmFsdWUgb2Ygb3B0aW9uc1xuXHRcdFx0c2hhcGUuc2V0QXR0cmlidXRlTlMobnVsbCwgXCIje29wdGlvbn1cIiwgXCIje29wdGlvbnNbb3B0aW9uXX1cIilcblxuXHRcdEBzdmcuYXBwZW5kQ2hpbGQoc2hhcGUpXG5cdFx0QHNoYXBlc1tcIiN7b3B0aW9ucy5pZH1cIl0gPSBzaGFwZVxuXG5cdFx0cmV0dXJuIHNoYXBlXG5cblx0YWRkTWFzazogKGlkKSAtPlxuXHRcdG1hc2sgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50TlMoXCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiLCBcIm1hc2tcIilcblx0XHRtYXNrLnNldEF0dHJpYnV0ZU5TKG51bGwsIFwiaWRcIiwgXCIje2lkfVwiKVxuXG5cdFx0ZGVmcyA9IEAuc3ZnLmdldEVsZW1lbnRzQnlUYWdOYW1lKFwiZGVmc1wiKVswXVxuXHRcdGRlZnMuYXBwZW5kQ2hpbGQobWFzaylcblxuXHRhZGRUb01hc2s6IChlbGVtZW50LCBpZCkgLT5cblx0XHRtYXNrID0gQC5zdmcuZ2V0RWxlbWVudEJ5SWQoXCIje2lkfVwiKVxuXHRcdG1hc2suYXBwZW5kQ2hpbGQoZWxlbWVudClcblxuXHRzZXRNYXNrOiAoZWxlbWVudCwgaWQpIC0+XG5cdFx0aWYgdHlwZW9mKGlkKSBpc250IFwic3RyaW5nXCJcblx0XHRcdGlkID0gaWQuZ2V0QXR0cmlidXRlTlMobnVsbCwgXCJpZFwiKVxuXG5cdFx0ZWxlbWVudC5zZXRBdHRyaWJ1dGVOUyhudWxsLCBcIm1hc2tcIiwgXCJ1cmwoIyN7aWR9KVwiKVxuXHRcdCIsIi8vIEdlbmVyYXRlZCBieSBDb2ZmZWVTY3JpcHQgMS45LjFcbnZhciBleHRlbmQgPSBmdW5jdGlvbihjaGlsZCwgcGFyZW50KSB7IGZvciAodmFyIGtleSBpbiBwYXJlbnQpIHsgaWYgKGhhc1Byb3AuY2FsbChwYXJlbnQsIGtleSkpIGNoaWxkW2tleV0gPSBwYXJlbnRba2V5XTsgfSBmdW5jdGlvbiBjdG9yKCkgeyB0aGlzLmNvbnN0cnVjdG9yID0gY2hpbGQ7IH0gY3Rvci5wcm90b3R5cGUgPSBwYXJlbnQucHJvdG90eXBlOyBjaGlsZC5wcm90b3R5cGUgPSBuZXcgY3RvcigpOyBjaGlsZC5fX3N1cGVyX18gPSBwYXJlbnQucHJvdG90eXBlOyByZXR1cm4gY2hpbGQ7IH0sXG4gIGhhc1Byb3AgPSB7fS5oYXNPd25Qcm9wZXJ0eTtcblxuZXhwb3J0cy5MYXllclNWRyA9IChmdW5jdGlvbihzdXBlckNsYXNzKSB7XG4gIGV4dGVuZChMYXllclNWRywgc3VwZXJDbGFzcyk7XG5cbiAgZnVuY3Rpb24gTGF5ZXJTVkcob3B0aW9ucykge1xuICAgIGlmIChvcHRpb25zID09IG51bGwpIHtcbiAgICAgIG9wdGlvbnMgPSB7fTtcbiAgICB9XG4gICAgTGF5ZXJTVkcuX19zdXBlcl9fLmNvbnN0cnVjdG9yLmNhbGwodGhpcywgb3B0aW9ucyk7XG4gICAgdGhpcy5zaGFwZXMgPSB7fTtcbiAgICB0aGlzLm1hc2tzID0ge307XG4gICAgdGhpcy5odG1sID0gXCI8c3ZnIGlkPSdcIiArIG9wdGlvbnMuaWQgKyBcIicgd2lkdGg9J1wiICsgdGhpcy53aWR0aCArIFwiJyBoZWlnaHQ9J1wiICsgdGhpcy5oZWlnaHQgKyBcIic+PGRlZnM+PC9kZWZzPjwvc3ZnPlwiO1xuICAgIHRoaXMuc3ZnID0gdGhpcy5xdWVyeVNlbGVjdG9yKFwiI1wiICsgb3B0aW9ucy5pZCk7XG4gIH1cblxuICBMYXllclNWRy5wcm90b3R5cGUuYWRkU2hhcGUgPSBmdW5jdGlvbih0eXBlLCBvcHRpb25zKSB7XG4gICAgdmFyIG9wdGlvbiwgc2hhcGUsIHZhbHVlO1xuICAgIGlmIChvcHRpb25zID09IG51bGwpIHtcbiAgICAgIG9wdGlvbnMgPSB7fTtcbiAgICB9XG4gICAgc2hhcGUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50TlMoXCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiLCBcIlwiICsgdHlwZSk7XG4gICAgZm9yIChvcHRpb24gaW4gb3B0aW9ucykge1xuICAgICAgaWYgKCFoYXNQcm9wLmNhbGwob3B0aW9ucywgb3B0aW9uKSkgY29udGludWU7XG4gICAgICB2YWx1ZSA9IG9wdGlvbnNbb3B0aW9uXTtcbiAgICAgIHNoYXBlLnNldEF0dHJpYnV0ZU5TKG51bGwsIFwiXCIgKyBvcHRpb24sIFwiXCIgKyBvcHRpb25zW29wdGlvbl0pO1xuICAgIH1cbiAgICB0aGlzLnN2Zy5hcHBlbmRDaGlsZChzaGFwZSk7XG4gICAgdGhpcy5zaGFwZXNbXCJcIiArIG9wdGlvbnMuaWRdID0gc2hhcGU7XG4gICAgcmV0dXJuIHNoYXBlO1xuICB9O1xuXG4gIExheWVyU1ZHLnByb3RvdHlwZS5hZGRNYXNrID0gZnVuY3Rpb24oaWQpIHtcbiAgICB2YXIgZGVmcywgbWFzaztcbiAgICBtYXNrID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudE5TKFwiaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmdcIiwgXCJtYXNrXCIpO1xuICAgIG1hc2suc2V0QXR0cmlidXRlTlMobnVsbCwgXCJpZFwiLCBcIlwiICsgaWQpO1xuICAgIGRlZnMgPSB0aGlzLnN2Zy5nZXRFbGVtZW50c0J5VGFnTmFtZShcImRlZnNcIilbMF07XG4gICAgcmV0dXJuIGRlZnMuYXBwZW5kQ2hpbGQobWFzayk7XG4gIH07XG5cbiAgTGF5ZXJTVkcucHJvdG90eXBlLmFkZFRvTWFzayA9IGZ1bmN0aW9uKGVsZW1lbnQsIGlkKSB7XG4gICAgdmFyIG1hc2s7XG4gICAgbWFzayA9IHRoaXMuc3ZnLmdldEVsZW1lbnRCeUlkKFwiXCIgKyBpZCk7XG4gICAgcmV0dXJuIG1hc2suYXBwZW5kQ2hpbGQoZWxlbWVudCk7XG4gIH07XG5cbiAgTGF5ZXJTVkcucHJvdG90eXBlLnNldE1hc2sgPSBmdW5jdGlvbihlbGVtZW50LCBpZCkge1xuICAgIGlmICh0eXBlb2YgaWQgIT09IFwic3RyaW5nXCIpIHtcbiAgICAgIGlkID0gaWQuZ2V0QXR0cmlidXRlTlMobnVsbCwgXCJpZFwiKTtcbiAgICB9XG4gICAgcmV0dXJuIGVsZW1lbnQuc2V0QXR0cmlidXRlTlMobnVsbCwgXCJtYXNrXCIsIFwidXJsKCNcIiArIGlkICsgXCIpXCIpO1xuICB9O1xuXG4gIHJldHVybiBMYXllclNWRztcblxufSkoTGF5ZXIpO1xuIiwiIyBBZGQgdGhlIGZvbGxvd2luZyBsaW5lIHRvIHlvdXIgcHJvamVjdCBpbiBGcmFtZXIgU3R1ZGlvLiBcbiMgbXlNb2R1bGUgPSByZXF1aXJlIFwibXlNb2R1bGVcIlxuIyBSZWZlcmVuY2UgdGhlIGNvbnRlbnRzIGJ5IG5hbWUsIGxpa2UgbXlNb2R1bGUubXlGdW5jdGlvbigpIG9yIG15TW9kdWxlLm15VmFyXG5cbmV4cG9ydHMubXlWYXIgPSBcIm15VmFyaWFibGVcIlxuXG5leHBvcnRzLm15RnVuY3Rpb24gPSAtPlxuXHRwcmludCBcIm15RnVuY3Rpb24gaXMgcnVubmluZ1wiXG5cbmV4cG9ydHMubXlBcnJheSA9IFsxLCAyLCAzXSJdfQ==
